/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_based_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Khanyisani
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }
    
        Connection con=null;
        ResultSet rs=null;
PreparedStatement pst=null;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtAdress = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtContact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboboxBlood = new javax.swing.JComboBox<>();
        comboboxGender = new javax.swing.JComboBox<>();
        txtSpecialization = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Admin Page");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Register Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, 140, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Surname");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, -1));
        jPanel1.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 350, 30));
        jPanel1.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 350, 30));
        jPanel1.add(jtxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 350, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));
        jPanel1.add(jtxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Adress");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));
        jPanel1.add(jtxtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 350, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose A Privilege Below", "Nurse", "Doctor", "Patient" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 340, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));
        jPanel1.add(jtxtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 350, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Contact ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));
        jPanel1.add(jtxtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 350, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Age");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        comboboxBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O", "A", "B", "AB", "" }));
        jPanel1.add(comboboxBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 350, 30));

        comboboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(comboboxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 350, 30));
        jPanel1.add(txtSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 350, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Blood Type");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 350, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Specialization");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 50, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Username");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 670, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             String Username = jtxtUsername.getText();
            String Identity = ID.getText();
            String Surname = jtxtSurname.getText();
            String Password = jtxtPassword.getText();
            String Address = jtxtAdress.getText();
            String Email= jtxtEmail.getText();
            String Contact= jtxtContact.getText();
            String Age = jtxtAge.getText();
            String BloodType =  (String) comboboxBlood.getSelectedItem();
             String gender = comboboxGender.getSelectedItem().toString();
             String specialization = txtSpecialization.getText();
             String date = txtDate.getText();
             
        con=Connect.ConnectDB();
        String comb2 = jComboBox2.getSelectedItem().toString();    
        if("Choose A Privilege Below".equals(comb2)){
  JOptionPane.showMessageDialog(this, "Please Choose A PRIVILAGA");
        }
   switch (comb2) {
                  case "Nurse":
            try {
            pst = con.prepareStatement("INSERT INTO `nurse`(`UserID`, `Username`, `Surname`, `Password`, `Address`, `Email`, `Contact`, `Age`, `specialization`, `Blood_Type`, `Gender`, `RegiterDate`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, Identity);
            pst.setString(2, Username);
            pst.setString(3, Surname);
            pst.setString(4, Password);
            pst.setString(5, Address);
            pst.setString(6, Email);
            pst.setString(7, Contact);
            pst.setString(8, Age);
            pst.setString(9 , specialization);
            pst.setString(10, BloodType);
            pst.setString(11, gender);
            pst.setString(12, date);
           
            int result = pst.executeUpdate();
       
       if(result == 1){
           JOptionPane.showMessageDialog(this, "Nurse Successfull Register");
              pst = con.prepareStatement("INSERT INTO `users`(`username`, `user_password`, `Privilege`) VALUES (?,?,?)");
                    pst.setString(1,Username);
                    pst.setString(2, Password);
                    pst.setString(3, "nurse");
                     if(pst.execute()){
                        super.dispose();
                        Login frm = new Login();
                        frm.setVisible(true);
                        JOptionPane.showMessageDialog(this, "Sucess...please login.");
                        }
                    }
                else{
                 JOptionPane.showMessageDialog(this, " Failed");
                     }
        } catch (SQLException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;
                
                
                
               case "Doctor":
          try {
            pst = con.prepareStatement("INSERT INTO `doctor`(`UserID`, `Username`, `Surname`, `Password`, `Address`, `Email`, `Contact`, `Age`, `specialization`, `Blood_Type`, `Gender`, `RegiterDate`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, Identity);
            pst.setString(2, Username);
            pst.setString(3, Surname);
            pst.setString(4, Password);
            pst.setString(5, Address);
            pst.setString(6, Email);
            pst.setString(7, Contact);
            pst.setString(8, Age);
            pst.setString(9 , specialization);
            pst.setString(10, BloodType);
            pst.setString(11, gender);
            pst.setString(12, date);
           
            int result = pst.executeUpdate();
       
       if(result == 1){
             JOptionPane.showMessageDialog(this, "doctor Successfull Register");
              pst = con.prepareStatement("INSERT INTO `users`(`username`, `user_password`, `Privilege`) VALUES (?,?,?)");
                    pst.setString(1,Username);
                    pst.setString(2, Password);
                    pst.setString(3, "doctor");
                     if(pst.execute()){
                        super.dispose();
                        Login frm = new Login();
                        frm.setVisible(true);
                        JOptionPane.showMessageDialog(this, "Sucess...please login.");

                    }
       }
       else{
           JOptionPane.showMessageDialog(this, " Failed");
       }
       
  } catch (SQLException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
          break;
             default:
        break;
             
            }   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JComboBox<String> comboboxBlood;
    private javax.swing.JComboBox<String> comboboxGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxtAdress;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JTextField jtxtContact;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtPassword;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtUsername;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
