package hospital_based_system;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Khanyisani
 */
public final class DoctorDash extends javax.swing.JFrame {
 String doctor_ID = "";
  Connection con=null;
ResultSet rs=null;
DefaultTableModel model;
PreparedStatement pst=null;
    /**
     * Creates new form DoctorDash
     */
    public DoctorDash(String d_ID) {
        this.doctor_ID = d_ID;
        initComponents();
       // JOptionPane.showMessageDialog(null,doctor_ID);
        loadTable();
    }

    void loadTable(){
    //SELECT `id`, `DOCTOR_ID`, `PATIENT_ID`, `SYSPTOMS`, `DIAGNOSIS`, `MEDICATION`, `date` FROM `appointment` WHERE 1
        try {
            
                String f = doctor_ID;
        con=Connect.ConnectDB();
                                                                                                                                                                   
            pst = con.prepareStatement("SELECT `id`, `DOCTOR_ID`, `PATIENT_ID`, `SYSPTOMS`, `DIAGNOSIS`, `MEDICATION`, `date` FROM `appointment`  WHERE `DOCTOR_ID` = ? ");
            pst.setString(1, f);
            rs = pst.executeQuery();

             model = (DefaultTableModel)jTable1.getModel();
             
            while(rs.next()){
           JOptionPane.showMessageDialog(this,"Auto Increment  :" + rs.getString(1));
           
           model.addRow(new Object[]{
            rs.getString(1),
            rs.getString(3),
            rs.getString(5),
            rs.getString(6),
            rs.getString(7),
            rs.getString(4)

        });
           
            }
            
           // jTable1.add(model);
            /*
            
                    pst = con.prepareStatement("SELECT `id`, `DOCTOR_ID`, `PATIENT_ID`, `SYSPTOMS`, `DIAGNOSIS`, `MEDICATION`, `date` FROM `appointment` WHERE DOCTOR_ID='"+doctor_ID+"' ");
                     rs = pst.executeQuery();
                     
                    // rs.getString(1);
                     String a ="";
                    while(rs.next())
                    { a =rs.getString(1);}
                    JOptionPane.showMessageDialog(this,"Auto Increment" +a);
         
                    JOptionPane.showMessageDialog(this,"success!"); */
                } catch (SQLException ex) {
                    Logger.getLogger(DoctorDash.class.getName()).log(Level.SEVERE, null, ex);
                }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Welcome Back Doc");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Slot", "Patient_ID", "Diagnosis", "Medications", "Date", "Symptoms"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        
      /*
         for(int i=0; i<jTable1.getRowCount(); i++){
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }
        
        */
      
      
        con=Connect.ConnectDB();
      String id =jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
      String Medication = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
      String Diagonis = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();

        try {
         pst = con.prepareStatement("UPDATE `appointment` SET `DIAGNOSIS`=?,`MEDICATION`=? WHERE id = '"+id+"'");
          pst.setString(1, Diagonis);
          pst.setString(2, Medication);
          
         int result = pst.executeUpdate();
       
       if(result == 1){
           JOptionPane.showMessageDialog(this, "Successfull Updated");
         /*  txtProductName.setText(""); 
           txtProductPrices.setText(""); 
           txtProductQuantity.setText("");
           */
       }
       else{
           JOptionPane.showMessageDialog(this, " Failed To Update");
       }
         
        } catch (SQLException ex) {
            Logger.getLogger(NurseProfile.class.getName()).log(Level.SEVERE, null, ex);
        }

      
      //
      
       
        JOptionPane.showMessageDialog(null, "");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DoctorDash(doctor_ID).setVisible(true);
                
               
            
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
