
package hospital_based_system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.LocalDate; // import the LocalDate class

/**
 *
 * @author Khanyisani
 */
public class NurseProfile extends javax.swing.JFrame {

  Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    
    /**
     * Creates new form NurseProfile
     */
    public NurseProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnSearchP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTfullname = new javax.swing.JTextField();
        TXTusername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXTaddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboboxGender = new javax.swing.JComboBox<>();
        TXTpassword = new javax.swing.JPasswordField();
        comboboxBlood = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TXTcontact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TXTpassword1 = new javax.swing.JPasswordField();
        UserID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        btnSearchP1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPatientSymtoms = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtPatientID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDoctorID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Nurse DashBoard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 216, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 110, 60));

        btnSearchP.setText("Search Patient");
        btnSearchP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearchP, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 110, 50));

        jLabel3.setText("Gender");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel2.setText("Patient Fullname");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        jPanel2.add(TXTfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 300, 31));
        jPanel2.add(TXTusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 300, 31));

        jLabel4.setText("Search By ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));
        jPanel2.add(TXTaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 300, 30));

        jLabel5.setText("Blood Type");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel6.setText("Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel7.setText("Address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel8.setText("Register Patient");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        comboboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel2.add(comboboxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 300, 30));
        jPanel2.add(TXTpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 300, 30));

        comboboxBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O", "A", "B", "AB", "" }));
        jPanel2.add(comboboxBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 300, 30));

        jLabel9.setText("Contact");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));
        jPanel2.add(TXTcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 300, 31));

        jLabel10.setText("UserID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 10));

        jLabel14.setText("Confirm Password");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel2.add(TXTpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 300, 30));

        UserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDActionPerformed(evt);
            }
        });
        jPanel2.add(UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 290, 30));

        jLabel16.setText("Patient Username");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 30, 30));

        btnSearchP1.setText("View Reply");
        btnSearchP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchP1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearchP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 110, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 650, 480));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("Make An Appointment");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));
        jPanel3.add(txtPatientSymtoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 290, 170));

        jButton3.setText("Make Appointment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 140, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Write Patient Symtoms");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel15.setText("Enter Patient ID");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jButton4.setText("Search Doctor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 140, 40));

        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 30, 30));

        jLabel17.setText("Search Doctor");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        txtDoctorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 30, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 430, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 1220, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        con=Connect.ConnectDB();
        String id = UserID.getText();
        String username = TXTusername.getText();
        String fname = TXTfullname.getText();
        String password = Arrays.toString(TXTpassword.getPassword());
        String password1 = Arrays.toString(TXTpassword1.getPassword());
        String blood = comboboxBlood.getSelectedItem().toString();
        String gender = comboboxGender.getSelectedItem().toString();
        String address = TXTaddress.getText();
        String contact = TXTcontact.getText();

        try {
            pst = con.prepareStatement("INSERT INTO `patient_registration`(`P_id`, `username`, `fullname`, `password`, `bloodType`, `gender`, `address`, `contact`) VALUES (?,?,?,?,?,?,?,?)");
            pst.setString(1,id);
            pst.setString(2,username);
            pst.setString(3, fname);
            if(password.equals(password1)){
                pst.setString(4,password1);
                pst.setString(5, blood);
                pst.setString(6, gender);
                pst.setString(7,address);
                pst.setString(8,contact);
                int res = pst.executeUpdate();
                if(res == 1){
                    JOptionPane.showMessageDialog(this,"success!");
                    //con=Connect.ConnectDB();
                    //"INSERT INTO `users`(`username`, `user_password`, `Privilege`) VALUES (
                    pst = con.prepareStatement("insert into users(username,user_password,Privilege)values(?,?,?)");
                    pst.setString(1,username);
                    pst.setString(2, password1);
                    pst.setString(3, "patient");
                    if(pst.execute()){
                        super.dispose();
                        Login frm = new Login();
                        frm.setVisible(true);
                        JOptionPane.showMessageDialog(this, "Sucess...please login.");

                    }

                }

            }else{
                JOptionPane.showMessageDialog(this,"Password do not match...failed!");
                super.dispose();Login log = new Login();log.setVisible(true);}

        } catch (SQLException ex) {
            Logger.getLogger(NurseProfile.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnSearchPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPActionPerformed
        // TODO add your handling code here:
        String f = txtID1.getText();
        con=Connect.ConnectDB();
        try {
            pst = con.prepareStatement("SELECT * FROM `patient_registration` WHERE `ID` = ? ");
            pst.setString(1, f);
            rs = pst.executeQuery();

            while(rs.next()){
                UserID.setText(rs.getString(2));
                TXTusername.setText(rs.getString(3));
                TXTfullname.setText(rs.getString(4));
                TXTpassword.setText(rs.getString(5));
                TXTpassword1.setText(rs.getString(5));
                if(rs.getString(6).equals("O")){
                    comboboxBlood.setSelectedIndex(0);
                }
                if(rs.getString(6).equals("A")){
                    comboboxBlood.setSelectedIndex(1);
                }
                if(rs.getString(6).equals("B")){
                    comboboxBlood.setSelectedIndex(2);
                }
                if(rs.getString(6).equals("AB")){
                    comboboxBlood.setSelectedIndex(3);
                }
                if(rs.getString(7).equals("M")){
                    comboboxGender.setSelectedIndex(0);
                }
                if(rs.getString(7).equals("F")){
                    comboboxGender.setSelectedIndex(1);
                }
                TXTaddress.setText(rs.getString(8));
                TXTcontact.setText(rs.getString(9));
            }

            JOptionPane.showMessageDialog(this, "record selected");
        } catch (SQLException ex)
        {
            Logger.getLogger(NurseProfile.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "record NOT slected  :( ");
        }
    }//GEN-LAST:event_btnSearchPActionPerformed

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      con=Connect.ConnectDB();
        String doctorID = txtDoctorID.getText();
        String P_id = txtPatientID.getText();
        String Symtoms = txtPatientSymtoms.getText();
          LocalDate myObj = LocalDate.now(); 
          
        try {
            //
            
            pst = con.prepareStatement("SELECT * FROM `appointment` WHERE `DOCTOR_ID` = '"+doctorID+"' AND `DATE` = '"+myObj.toString()+"'");
            
            ResultSet rst = pst.executeQuery();
            int c = 0;
            while(rst.next()){
                ++c;
            }
           
            if(c < 5){
            pst = con.prepareStatement("INSERT INTO `appointment`(`DOCTOR_ID`, `PATIENT_ID`, `SYSPTOMS`,`DIAGNOSIS`,`MEDICATION`,`date`) VALUES (?,?,?,?,?,?)");
            pst.setString(1,doctorID);
            pst.setString(2,P_id);
            pst.setString(3, Symtoms);
            pst.setString(4, "");
            pst.setString(5, "");
            pst.setString(6 , myObj.toString());
                int res = pst.executeUpdate();
                if(res == 1){
                    JOptionPane.showMessageDialog(this,"Appointment Succesfull Made!");
              
                        JOptionPane.showMessageDialog(this, "Sucess...please login.");

                    }

            }else{
             JOptionPane.showMessageDialog(null,"Doctor not Avaliable "+c);
            }

            }catch (SQLException ex) {
            Logger.getLogger(NurseProfile.class.getName()).log(Level.SEVERE, null, ex);
        }

         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        /////////////////For Doctor now am checking if the nurse id exit in the database before making the appointment
        String doctor_id = txtDoctorID.getText();
        String username = TXTusername.getText();
        String blood = comboboxBlood.getSelectedItem().toString();
        String gender = comboboxGender.getSelectedItem().toString();
        String PatientSymtoms = txtPatientSymtoms.getText();

        String P_id = txtPatientID.getText();
        con=Connect.ConnectDB();
        try {
            pst = con.prepareStatement("SELECT * FROM `doctor`");
           // pst.setString(1, P_id);
            rs = pst.executeQuery();
            while(rs.next()){
                
                if(doctor_id.equals(rs.getString(2))){
                  JOptionPane.showMessageDialog(this, "Doctor ID Is Avaliable");
                }else{
               JOptionPane.showMessageDialog(this, "Doctor ID not There");
                }
                //txtDoctorID.setText(rs.getString(2));  
                    }
        } catch (SQLException ex)
        {
            Logger.getLogger(NurseProfile.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "record NOT slected  :( ");
        }

    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDActionPerformed

    private void txtID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1ActionPerformed

    private void txtDoctorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorIDActionPerformed

    private void btnSearchP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchP1ActionPerformed
                    this.dispose();
                      NurseCC frm=new NurseCC();
                       frm.setVisible(true);      
        
        
    }//GEN-LAST:event_btnSearchP1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NurseProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NurseProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NurseProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NurseProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NurseProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTaddress;
    private javax.swing.JTextField TXTcontact;
    private javax.swing.JTextField TXTfullname;
    private javax.swing.JPasswordField TXTpassword;
    private javax.swing.JPasswordField TXTpassword1;
    private javax.swing.JTextField TXTusername;
    private javax.swing.JTextField UserID;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSearchP;
    private javax.swing.JButton btnSearchP1;
    private javax.swing.JComboBox<String> comboboxBlood;
    private javax.swing.JComboBox<String> comboboxGender;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientSymtoms;
    // End of variables declaration//GEN-END:variables
}
